### PR TITLE
CreateProcess Review

### PR DESCRIPTION
**Pull request by exvito**
Oliver,

I've been going through the changes for the CreateProcess implementation.
I'm submitting this PR, for now, fixing a few missing / duplicate constants.

I have a few questions that I list below to better understand your decisions (I hope you don't mind me asking them -- I'm just humbly sharing my curiosity so as to better focus my future contributions):
- What's the use case of returning `lpCommandLine` in the `CreateProcessResult` tuple? As far as I could tell, it's never changed -- so its returned pretty much as supplied in the argument, isn't it?
- I not 100% sure I understand the idea around the `module_name` function -- is it there just for a more clear error message? If so, which would be the underlying windows error message? (it's a lot of code to for the sake of a nicer message which, when faced with, a user won't probably be able to google as easily as a "standard" windows message; iow, is it really worth it?).
- Regarding the `text_to_wchar()` function in wintypes/functions:
  *\* I understand the particular case for its usage in building the environment buffer.
  *\* Other than that, CFFI handles Python strings vs. C's wchar conversions by itself, doesn't it?
  *\* If that is the case -- correct me, please, if I'm wrong -- wouldn't it be somehow cleaner to have the `text_to_wchar` just be a private method in process.py much like `environment_to_string()`, given that any other "regular" string <-> wchar conversion is handled by CFFI itself?

A last comment, for now, is related to the initial validations: given that `wintype_to_cdata()` will return ffi.NULL when its argument is None, most of the code can be simplified I believe.

We can go from the current 7 line if statement:

```
    if lpProcessAttributes is not None:                                                   
        input_check(
            "lpProcessAttributes", lpProcessAttributes,
            allowed_types=(SECURITY_ATTRIBUTES, ))
        lpProcessAttributes = wintype_to_cdata(lpProcessAttributes)
    else:
        lpProcessAttributes = ffi.NULL
```

to shorter 4 line no-if-needed code, just by adding NoneType to the allowed_types:

```
    input_check(
        "lpProcessAttributes", lpProcessAttributes,
        allowed_types=(SECURITY_ATTRIBUTES, NoneType))
    lpProcessAttributes = wintype_to_cdata(lpProcessAttributes)
```

Please let my know of your thoughts on these topics.
Thanks in advance.

### CODE REVIEW

**Comment by opalmer** [comment]
> What's the use case of returning lpCommandLine in the CreateProcessResult tuple? 
> So the reason I'm returning it was mainly for consistency.  In every other case where a function argument is marked as input and output I've usually returned the object from the function call.  I've read over the docs again and at least from what I can tell it's not normally modified so removing it from the output may make sense.
> 
> I not 100% sure I understand the idea around the module_name function 

At the moment, it is to help create a better error message.  If you think it would be better to not perform the extra check I'd be ok with that.  But, we probably should keep the function around so someone can use it to determine the module name should they need it in their own calls to CreateProcess.  Thoughts?

> If that is the case -- correct me, please, if I'm wrong -- wouldn't it be somehow cleaner to have the text_to_wchar just be a private method in process.py much like environment_to_string()

Seems like a logical change to me.  Probably don't even need to make it a function and instead just inline that code as part of CreateProcess.

> We can go from the current 7 line if statement: ... to shorter 4 line no-if-needed code, just by adding NoneType to the allowed_types:

The shorter version looks much better.  The code as it's written now is probably left over from me copy/pasting code as I was implementing CreateProcess.

**Comment by exvito** [comment]
My suggestions:
- Not sure about the `module_name` function and not 100% familiar with Windows details so for now I find no good reason to change it. I was just trying to understand it completely.
- Regarding `text_to_wchar` -- I understand the temptation to inline it in `CreateProcess` but in the grand scheme of things, keeping it separate will result in more explicit code. So I'd just move it to a private function in kernel32\process.py.

So, if it's ok with you, I'll go ahead and move the `test_to_wchar` and simplify the `input_check` validation in CreateProcess.

**Comment by opalmer** [comment]
👍 , sounds good.

**Comment by opalmer** [comment]
Changes look good, ready to merge if you think it's ready.

**Comment by exvito** [comment]
I agree. Please go ahead and merge.

**Pull request merged**
