### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by opalmer**

### CODE REVIEW

**Comment by opalmer** [comment]
@exvito, take a look.  Once this build finishes this PR can merge and I'll make a release with your code tomorrow (it will take a while for AppyVeyor to finish).  Thanks again!

**Comment by exvito** [comment]
That's great. Thanks.
I will continue contributing but very busy this week. Expect feedback soon.

**Comment by exvito** [comment]
Quick question (pardon my ignorance): shouldn't this merge lead to a release on PyPI?

**Comment by opalmer** [comment]
Yes and no.  I make releases by running `tools\release.py` which then downloads the wheels from AppVeyor, uploads them to PyPi and creates the release on GitHub too.  However, for one of the wheels PyPi responded with an internal server error so I ended uploading the rest by hand except for the source zip (forgot about it since we have wheels).

0.2.0 has been up on PyPi for four but after looking at it again today, pip itself didn't see it.  Looks like pip will ignore any release that does not contain a source zip file even if there are wheels available and previous releases are hidden.

Sorry about that....

**Comment by exvito** [comment]
Thanks for the clarification. I looks fine now: I just pip installed and it brought in 0.2.0. :)

**Pull request merged**
