### PR TITLE
Use str.format(), and unicode string literals in a few places

### PR DESCRIPTION
**Pull request by rodrigc**
Fixes https://github.com/opalmer/pywincffi/issues/134

### CODE REVIEW

**Comment by opalmer** [comment]
@rodrigc, thanks! I took a glance at the code and assuming the tests pass I'll be happy to merge this tomorrow. Do you think this will fix the issue you're having in #134?

**Review by opalmer — APPROVED** [review]

**Comment by opalmer** [comment]
Hey @rodrigc, should I go ahead and merge this or are you still working on it?

**Comment by rodrigc** [comment]
@opalmer: I'm done with this branch.  Please look.

**Comment by opalmer** [comment]
Looks good, and thanks for the fix and taking the time to look at this. I'll make and update to the changelog once both of your changes merge so you don't have to rebase/wait for another build.

**Pull request merged**
